plugins {
    id "java-common-conventions"
    id "java-publishing-conventions"
    id "scala-common-conventions"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

dependencies {
    api project(":api-legacy")
    implementation project(":memory")
    compileOnly "org.joda:joda-convert:1.3.1"
    implementation "org.scala-lang:scala-library:$scalaVersion"

    testImplementation project(":api-legacy:testlib")
    testImplementation libs.bundles.junit
    testImplementation libs.timgroup.clocks.joda.testing
    testImplementation libs.timgroup.clocks.testing
    testImplementation "org.scalatest:scalatest_$scalaApiVersion:3.0.8"
    testCompileOnly "org.joda:joda-convert:1.3.1"
    testRuntimeOnly "org.pegdown:pegdown:1.4.2"
}

tasks.named("jar").configure {
    manifest {
        attributes(
                'Automatic-Module-Name': "com.timgroup.eventstore.memory.legacy"
        )
    }
}

timgroupRepo {
    artifactId = "eventstore-memory-legacy_${scalaApiVersion}"
}
