plugins {
    id "java-common-conventions"
    id "java-publishing-conventions"
    id "scala-common-conventions"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

dependencies {
    api project(":api-legacy")
    api libs.junit
    api libs.hamcrest.core
    api "org.scalatest:scalatest_$scalaApiVersion:3.0.8"
    implementation libs.hamcrest.library
}

timgroupRepo {
    artifactId = "eventstore-api-legacy-testlib_${scalaApiVersion}"
}
